staging/lustre/obdclass: fix missing symbols when CONFIG_PROC_FS is off
We need to define and export
obd_max_pages/obd_max_alloc/obd_alloc/obd_pages.
Otherwise build would get errors like:

ERROR: "obd_alloc" [drivers/staging/lustre/lustre/fld/fld.ko] undefined!
ERROR: "obd_max_alloc" [drivers/staging/lustre/lustre/fld/fld.ko] undefined!

Signed-off-by: Peng Tao <bergwolf@gmail.com>